name: Deploy Terraform - OIDC

on:
    workflow_dispatch:
        inputs:
            target_account:
                description: "Selecciona la cuenta a desplegar"
                required: true
                type: choice
                options:
                    - tooling
                    - connectivity
                    - production
            terraform_action:
                description: "Acci√≥n a ejecutar"
                required: true
                default: "plan"
                type: choice
                options:
                    - plan
                    - apply

env:
    AWS_REGION: "us-east-1"
    WORK_DIR: "accounts/${{ github.event.inputs.target_account }}"

jobs:
    terraform:
        name: TF ${{ inputs.terraform_action }} on ${{ inputs.target_account }}
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform CLI
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: "1.14.3"

            - name: Configure AWS credentials - OIDC
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Terraform init
              working-directory: ${{ env.WORK_DIR }}
              run: |
                  terraform init \
                    -backend-config="bucket=${{ secrets.S3_STATE }}" \
                    -backend-config="key=${{ env.WORK_DIR }}/terraform.tfstate" \
                    -backend-config="region=${{ env.AWS_REGION }}"

            - name: Terraform Validate
              working-directory: ${{ env.WORK_DIR }}
              run: terraform validate

            - name: Terraform Plan
              working-directory: ${{ env.WORK_DIR }}
              run: terraform plan -out=plan.tfplan -var="s3_state=${{ secrets.S3_STATE }}"

            - name: Terraform Apply
              if: ${{ inputs.terraform_action == 'apply' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform apply -auto-approve plan.tfplan
