name: Deploy Terraform - OIDC

on:
    workflow_dispatch:
        inputs:
            target_account:
                description: "Selecciona la cuenta a desplegar"
                required: true
                type: choice
                options:
                    - connectivity
                    - production
            terraform_action:
                description: "Acción a ejecutar"
                required: true
                default: "plan"
                type: choice
                options:
                    - plan
                    - apply
                    - destroy
                    - unlock
            lock_id:
                description: "ID de bloqueo (Solo para la opción unlock)"
                required: false
                type: string

env:
    AWS_REGION: "us-east-1"
    WORK_DIR: "accounts/${{ github.event.inputs.target_account }}"

    TF_VAR_aws_region: "us-east-1"
    TF_VAR_project_name: "terra-lading-zone"
    TF_VAR_s3_state: ${{ secrets.S3_STATE }}

jobs:
    terraform:
        name: TF ${{ inputs.terraform_action }} on ${{ inputs.target_account }}
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform CLI
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: "1.14.3"

            - name: Configure AWS credentials - OIDC
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Terraform init
              working-directory: ${{ env.WORK_DIR }}
              run: |
                  terraform init \
                    -backend-config="bucket=${{ secrets.S3_STATE }}" \
                    -backend-config="key=${{ env.WORK_DIR }}/terraform.tfstate" \
                    -backend-config="region=${{ env.AWS_REGION }}"

            - name: Terraform Force Unlock
              if: ${{ github.event.inputs.lock_id != '' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform force-unlock -force ${{ github.event.inputs.lock_id }}

            - name: Terraform Validate
              if: ${{ github.event.inputs.terraform_action != 'unlock' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform validate

            - name: Terraform Plan
              if: ${{ github.event.inputs.terraform_action != 'unlock' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform plan -out=plan.tfplan

            - name: Terraform Apply
              if: ${{ inputs.terraform_action == 'apply' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform apply -auto-approve plan.tfplan

            - name: Terraform Destroy
              if: ${{ github.event.inputs.terraform_action == 'destroy' }}
              working-directory: ${{ env.WORK_DIR }}
              run: terraform destroy -auto-approve
